### ISSUE TITLE
Spacing below leaflet widgets

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-r#18]
Unless https://github.com/rstudio/rmarkdown/issues/1343 is resolved, add custom CSS to vignette.

```css
.html-widget {
  margin: 0 0 10px;
}
```

**EDIT:** we still need https://github.com/r-lib/pkgdown/issues/667 fixed to have the widgets display properly in online docs.
